SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS signs;

SET FOREIGN_KEY_CHECKS=1;


CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(30) NOT NULL,
    
);

CREATE TABLE signs (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    sign_name VARCHAR(30) NOT NULL,
    begin_date VARCHAR(30) NOT NULL,
    end_date VARCHAR(30) NOT NULL,    
);