SET FOREIGN_KEY_CHECKS=0;

DROP DATABASE IF EXISTS user_db;
DROP DATABASE IF EXISTS signs_db;

SET FOREIGN_KEY_CHECKS=1;

CREATE DATABASE user_db;
CREATE DATABASE signs_db;

USE DATABASE user_db;
USE DATABASE signs_db;

